import "./globals.css"
import type { Metadata } from "next"
import SocketProvider from "@/context/SocketContext"
import Navbar from "@/common/Navbar"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <SocketProvider>
        <body className="flex"> 
            {children}
        </body>
      </SocketProvider>
    </html>
  )
}
